//! Cargo manifest, build script and Windows resources of the generated
//! installer crate.

use std::fmt::Write as _;
use std::path::Path;

use inst_model::privileges::Level;

use crate::input::CodegenInput;

fn toml_str(s: &str) -> String {
    toml::Value::String(s.to_owned()).to_string()
}

fn path_str(p: &Path) -> String {
    toml_str(&p.to_string_lossy().replace('\\', "/"))
}

/// `x.y.z` from the product version (Cargo requires SemVer).
fn semver(v: &inst_model::Version) -> String {
    let parts = v.parts();
    let get = |i: usize| parts.get(i).copied().unwrap_or(0);
    format!("{}.{}.{}", get(0), get(1), get(2))
}

pub fn cargo_toml(input: &CodegenInput<'_>, runtime_features: &[&str]) -> String {
    let p = input.project;
    let mut s = String::with_capacity(2048);
    let _ = writeln!(s, "# @generated by {}. Do not edit.", inst_brand::STUDIO_NAME);
    let _ = writeln!(
        s,
        "[package]\nname = \"setup\"\nversion = \"{}\"\nedition = \"2024\"\npublish = false\nbuild = \"build.rs\"\n",
        semver(&p.product.version)
    );
    s.push_str("[[bin]]\nname = \"setup\"\npath = \"src/main.rs\"\n\n");
    s.push_str("[dependencies]\n");
    let feats: Vec<String> = runtime_features.iter().map(|f| toml_str(f)).collect();
    let _ = writeln!(
        s,
        "inst-runtime = {{ path = {}, default-features = false, features = [{}] }}",
        path_str(&input.runtime.runtime),
        feats.join(", ")
    );
    if input.gui
        && let Some(ui) = &input.runtime.runtime_ui
    {
        let _ = writeln!(s, "inst-runtime-ui = {{ path = {} }}", path_str(ui));
    }
    // Stand-alone workspace so the crate never joins an enclosing one.
    s.push_str("\n[workspace]\n\n");
    // Installer release profile: size first, but the build system measures
    // the alternatives instead of assuming.
    let _ = writeln!(
        s,
        "[profile.release]\nopt-level = {}\nlto = \"fat\"\ncodegen-units = 1\npanic = \"abort\"\nstrip = \"symbols\"\ndebug = false\nincremental = false\ndebug-assertions = false\noverflow-checks = false\n",
        input.profile.opt_level()
    );
    // Hashing and decompression stay fast even in a size-optimized binary.
    for pkg in ["blake3", "zstd-sys", "liblzma-sys"] {
        let _ = writeln!(s, "[profile.release.package.{pkg}]\nopt-level = 3\n");
    }
    s
}

pub fn app_manifest(input: &CodegenInput<'_>) -> String {
    let level = if input.privileges.effective == Level::Admin {
        "requireAdministrator"
    } else {
        "asInvoker"
    };
    let id: String = input
        .project
        .product
        .id
        .as_str()
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '.' { c } else { '.' })
        .collect();
    format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <assemblyIdentity type="win32" name="{id}.Setup" version="1.0.0.0" processorArchitecture="*"/>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="{level}" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <supportedOS Id="{{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}}"/>
    </application>
  </compatibility>
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/pm</dpiAware>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>
      <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>
      <activeCodePage xmlns="http://schemas.microsoft.com/SMI/2019/WindowsSettings">UTF-8</activeCodePage>
    </windowsSettings>
  </application>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*"/>
    </dependentAssembly>
  </dependency>
</assembly>
"#
    )
}

fn rc_escape(s: &str) -> String {
    s.replace('"', "\"\"").replace(['\n', '\r'], " ")
}

/// Resource script: manifest, version information and (optionally) icon.
pub fn app_rc(input: &CodegenInput<'_>) -> String {
    let p = input.project;
    let q = p.product.version.windows_quad();
    let quad = format!("{},{},{},{}", q[0], q[1], q[2], q[3]);
    let mut s = String::new();
    s.push_str("#pragma code_page(65001)\n");
    s.push_str("1 24 \"app.manifest\"\n");
    if input.windows_icon.is_some() {
        s.push_str("1 ICON \"icon.ico\"\n");
    }
    let _ = write!(
        s,
        r#"1 VERSIONINFO
FILEVERSION {quad}
PRODUCTVERSION {quad}
FILEOS 0x40004
FILETYPE 0x1
BEGIN
  BLOCK "StringFileInfo"
  BEGIN
    BLOCK "040904B0"
    BEGIN
      VALUE "CompanyName", "{publisher}"
      VALUE "FileDescription", "{name} Setup"
      VALUE "FileVersion", "{version}"
      VALUE "ProductName", "{name}"
      VALUE "ProductVersion", "{version}"
      VALUE "OriginalFilename", "setup.exe"
    END
  END
  BLOCK "VarFileInfo"
  BEGIN
    VALUE "Translation", 0x409, 1200
  END
END
"#,
        publisher = rc_escape(&p.product.publisher),
        name = rc_escape(&p.product.name),
        version = rc_escape(&p.product.version.to_string()),
    );
    s
}

/// Build script: embeds the manifest/resources on Windows. MSVC links the
/// manifest directly; GNU targets compile `app.rc` with `windres`.
pub const BUILD_RS: &str = r#"// @generated. Embeds the Windows manifest and version resource.
use std::path::PathBuf;
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=app.manifest");
    println!("cargo:rerun-if-changed=app.rc");
    println!("cargo:rerun-if-env-changed=WINDRES");
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }
    let dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("out dir"));
    let env = std::env::var("CARGO_CFG_TARGET_ENV").unwrap_or_default();
    if env == "msvc" {
        let rc = std::env::var("RC").unwrap_or_else(|_| "rc.exe".into());
        let res = out.join("app.res");
        let ok = Command::new(&rc)
            .current_dir(&dir)
            .args(["/nologo", "/fo"])
            .arg(&res)
            .arg("app.rc")
            .status()
            .map(|s| s.success())
            .unwrap_or(false);
        if ok {
            println!("cargo:rustc-link-arg-bins={}", res.display());
        } else {
            println!("cargo:warning=rc.exe not found; embedding the manifest only (no version resource)");
            println!("cargo:rustc-link-arg-bins=/MANIFEST:EMBED");
            println!("cargo:rustc-link-arg-bins=/MANIFESTINPUT:{}", dir.join("app.manifest").display());
        }
        return;
    }
    let arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let candidates = [
        std::env::var("WINDRES").unwrap_or_default(),
        format!("{arch}-w64-mingw32-windres"),
        "windres".to_owned(),
    ];
    let res = out.join("app.res.o");
    for windres in candidates.iter().filter(|c| !c.is_empty()) {
        let ok = Command::new(windres)
            .current_dir(&dir)
            .args(["-J", "rc", "-O", "coff", "-i", "app.rc", "-o"])
            .arg(&res)
            .status()
            .map(|s| s.success())
            .unwrap_or(false);
        if ok {
            println!("cargo:rustc-link-arg-bins={}", res.display());
            return;
        }
    }
    panic!("windres not found: the installer manifest (UAC level) cannot be embedded");
}
"#;
